name: Collect Bsky Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update:
    name: Collect Bsky Posts
    runs-on: ubuntu-latest
    env:
      IDENTIFIER: ${{ secrets.IDENTIFIER }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U git+https://github.com/medialab/minet@2c87d16b

      - name: Scrape bsky posts
        run: minet bsky user-posts medialab-scpo.bsky.social --limit 50 --identifier "${IDENTIFIER}" --password "${PASSWORD}" > data/medialab_bsky_posts.csv

      - name: Check
        run : ls data

      - name: Commit enrichment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data
          git pull
          git commit -m "update data" data
          git push
